version: '3'
services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
    ports:
      - "5678:5678"
    volumes:
      - ~/.n8n:/root/.n8n
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
      - POSTGRES_DB=n8n
    volumes:
      - ~/.postgres-data:/var/lib/postgresql/data
    restart: always
