version: '3'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Sao_Paulo
    volumes:
      - ./n8n_data:/home/node/.n8n

  firebird:
    image: jacobalberty/firebird:2.5-ss
    container_name: firebird25
    ports:
      - "3050:3050"
    environment:
      - ISC_PASSWORD=masterkey
    volumes:
      - ./firebird_data:/firebird/data
      - ./employee.fbk:/firebird/employee.fbk
    restart: unless-stopped