version: '3'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=teste
      - N8N_BASIC_AUTH_PASSWORD=teste
    volumes:
      - ./n8n_data:/root/.n8n
    restart: always
