services:
  firebird:
    image: jacobalberty/firebird:2.5.9-ss
    container_name: n8n-firebird-1
    restart: unless-stopped
    ports:
      - "3050:3050"
    volumes:
      - ./backend:/firebird/data
    environment:
      ISC_PASSWORD: masterkey
    networks:
      - n8n-network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: n8n_api
    restart: unless-stopped
    env_file: .env
    environment:
      FIREBIRD_HOST: firebird
      FIREBIRD_PORT: 3050
      FIREBIRD_DATABASE: /firebird/data/EMPLOYEE.FDB
      FIREBIRD_USER: ${FIREBIRD_USER}
      ISC_PASSWORD: ${ISC_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/firebird/data
    depends_on:
      - firebird
    networks:
      - n8n-network

  n8n:
    image: n8nio/n8n:stable
    container_name: n8n-n8n-1
    restart: unless-stopped
    ports:
      - "5678:5678"
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge
